In [ ]:
########################################

In [6]:
#Import numpy 
import numpy as np 
import matplotlib.pyplot as plt

In [5]:
#creat nested list 
a =[[11,12,13],[21,22,23], [31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [7]:
#cast the list to numpy array 
array = np.array(a)
array


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
#Get the number of dimensions using ndim
dim=np.ndim(array)
print(dim)
type(dim)

2


int

In [9]:
#Get the number of each dimensions(rows and columns)
shape = np.shape(array)
print(shape)

(3, 3)


In [15]:
#Total number of elements in the array 
size = np.size(array)
size

9

In [10]:
#lenth of array is number of rows in array. 
lenght= len(array)
lenght 


3

In [11]:
len(array[0])

3

<h1> Accessing different elements of numpy array</h1>

In [13]:
#accessing second row 3rd column
array[1,2]

23

In [14]:
#3rd row 2nd column 
array[2,1]

32

<h1> Note : 0 is represeted as 1st row/1st column because lists start from 0 </h1>

In [15]:
#Access 1st row 1st column 
array[0,0]

11

In [19]:
#Access elements of 1st row 1column and 2nd column 
arr=array[0][0:2]
print(arr)

[11 12]


In [21]:
#Access all elements of 3rd row 
arr1=array[2][0:3]
print(arr1)

[31 32 33]


In [24]:
#access 2nd row 3rd row element of 2nd column 
print(array[1:3,1])

[22 32]


In [25]:
#Access the 3rd column elements
array[0:3][2]

array([31, 32, 33])

<h1> Basic operations on matrix </h1>


In [27]:
array1= [[2,3,4],[5,6,7],[12,31,23]]
array1

[[2, 3, 4], [5, 6, 7], [12, 31, 23]]

In [28]:
array2= [[21,32,43],[54,65,76],[2,1,3]]
array2

[[21, 32, 43], [54, 65, 76], [2, 1, 3]]

In [31]:
arr1= np.array(array1)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [12 31 23]]


In [32]:
arr2= np.array(array2)
print(arr2)

[[21 32 43]
 [54 65 76]
 [ 2  1  3]]


In [34]:
#Addition 
add=arr1+arr2
print(add)

[[23 35 47]
 [59 71 83]
 [14 32 26]]


In [36]:
#Substraction 
sub=arr1-arr2
print(sub)

[[-19 -29 -39]
 [-49 -59 -69]
 [ 10  30  20]]


<h1> Multiplication: don't forget for multiplication number of rows of 1st matrxi must be equal to number of columns of 2nd matrix</h1>

In [38]:
#Create arrays
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [40]:
y = np.array([[9,8,7],[6,5,4]])
print(y)

[[9 8 7]
 [6 5 4]]


<h4>Multiplication of two arrays corresponds to an element-wise product or Hadamard product. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position</h4>

We can perform element-wise product of the array <code>X</code> and <code>Y</code> as follows:

In [44]:
#Multiply 
z = x*y
z

array([[ 9, 16, 21],
       [24, 25, 24]])

<h2> Matrix multiplication </h2>


In [49]:
# Create a matrix A
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [50]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [53]:
#We use numpy dot function to perform matrix multiplication 
z = np.dot(A,B)
print(z)

[[0 2]
 [0 2]]


In [57]:
#Transpose of matrix can be performed using numpy attribute "T"
c = np.array([[2,3,4],[9,8,7]])
print("2 rows 3 columns\n", c) #  

2 rows 3 columns
 [[2 3 4]
 [9 8 7]]


In [62]:
#Transpose using "T"
transpose= c.T
print("transposed matrix\n2 columns 3 rows\n" ,transpose)

transposed matrix
2 columns 3 rows
 [[2 9]
 [3 8]
 [4 7]]
